name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download last release asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'hardymil/HelloWorld'
        version: 'tags/1.0'
        file: 'Talend_Change_Data_Capture.7.16.0.zip'
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>talend_nexus_deployment</id><username>${{ secrets.NEXUS_ID }}</username><password>${{ secrets.NEXUS_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn clean deploy:deploy-file -Dfile=Talend_Change_Data_Capture.7.16.0.zip -Dversion=7.16.0 -DartifactId=Talend_Change_Data_Capture_releases -DgroupId=org.talend.changedatacapture -DrepositoryId=talend_nexus_deployment -DrepositoryId=talend_nexus_deployment -Durl=https://artifacts-zl.talend.com/nexus/content/repositories/thirdparty-releases/ -Dtype=zip 
