name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Download last release asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'hardymil/HelloWorld'
        version: 'tags/1.0'
        file: 'Talend_Change_Data_Capture.7.16.0.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://artifacts-zl.talend.com/nexus/content/repositories/releases
        username: hmilalu
        password: ${{ secrets.NEXUS_PASSWORD }}
        format: maven2
        repository: talend_nexus_deployment
        coordinates: groupId=org.talend.changedatacapture artifactId=Talend_Change_Data_Capture_releases version=1.0.0
        assets: extension=zip
        filename: ./Talend_Change_Data_Capture.7.16.0.zip